# Generated by Django 5.0.3 on 2024-05-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="countries_visited",
            field=models.TextField(blank=True, null=True),
        ),
    ]
