# Generated by Django 5.0.3 on 2024-05-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_countries_visited"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="countries_visited",
        ),
        migrations.AddField(
            model_name="user",
            name="countries_visited",
            field=models.ManyToManyField(related_name="users", to="users.country"),
        ),
    ]
