# Generated by Django 5.0.3 on 2024-06-02 11:00

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_country_name_alter_user_countries_visited"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="countries_visited",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.AddField(
            model_name="user",
            name="countries_visited",
            field=django_countries.fields.CountryField(
                blank=True, max_length=746, multiple=True
            ),
        ),
    ]
