# Generated by Django 5.0.3 on 2024-05-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_countries_visited_user_visited_countries_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="visited_countries",
            field=models.TextField(blank=True, null=True),
        ),
    ]
