# Generated by Django 5.0.3 on 2024-06-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="countries_visited",
        ),
        migrations.AddField(
            model_name="user",
            name="countries_visited",
            field=models.ManyToManyField(blank=True, to="users.country"),
        ),
    ]
