# Generated by Django 5.0.3 on 2024-05-25 09:37

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_visited_countries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="visited_countries",
        ),
        migrations.AddField(
            model_name="user",
            name="countries_visited",
            field=django_countries.fields.CountryField(
                blank=True, max_length=746, multiple=True
            ),
        ),
    ]
