# Generated by Django 5.0.3 on 2024-05-25 09:44

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_visited_countries_user_countries_visited"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    django_countries.fields.CountryField(max_length=2, unique=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="countries_visited",
        ),
        migrations.AddField(
            model_name="user",
            name="countries_visited",
            field=models.ManyToManyField(blank=True, to="users.country"),
        ),
    ]
