# Generated by Django 5.0.3 on 2024-06-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_user_countries_visited_delete_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="countries_visited",
        ),
    ]
