# Generated by Django 5.0.3 on 2024-05-25 10:11

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_user_countries_visited_delete_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="countries_visited",
            field=django_countries.fields.CountryField(max_length=746, multiple=True),
        ),
    ]
