# Generated by Django 5.0.3 on 2024-06-02 15:36

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_country_user_countries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="countries",
        ),
        migrations.AddField(
            model_name="user",
            name="countries_visited",
            field=django_countries.fields.CountryField(
                blank=True, max_length=746, multiple=True
            ),
        ),
        migrations.DeleteModel(
            name="Country",
        ),
    ]
