# Generated by Django 5.0.3 on 2024-05-25 10:18

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_countries_visited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="countries_visited",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
