# Generated by Django 5.0.3 on 2024-06-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_user_countries_user_countries_visited_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="countries_visited",
        ),
    ]
