# Generated by Django 5.0.3 on 2024-06-04 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visited_countries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
