# Generated by Django 5.0.3 on 2024-06-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_country_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="countries_visited",
            field=models.ManyToManyField(
                blank=True, related_name="visited_by", to="users.country"
            ),
        ),
    ]
