# Generated by Django 5.0.3 on 2024-06-04 09:48

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_remove_country_user_user_countries_visited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
