# Generated by Django 5.0.3 on 2024-04-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="firstname",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="lastname",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
