# Generated by Django 5.0.3 on 2024-04-17 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0002_userprofile_firstname_userprofile_lastname"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_trips", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
