# Generated by Django 5.0.3 on 2024-04-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0003_trip_favorited_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="favorited_by",
        ),
    ]
