# Generated by Django 5.0.3 on 2024-07-06 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0003_category_trip_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trips",
                to="trip.category",
            ),
        ),
    ]
