# Generated by Django 5.0.3 on 2024-07-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0004_alter_trip_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="category",
        ),
        migrations.AddField(
            model_name="trip",
            name="categories",
            field=models.ManyToManyField(related_name="trips", to="trip.category"),
        ),
    ]
