# Generated by Django 5.0.3 on 2024-04-19 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0004_remove_trip_favorited_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="favourites",
            field=models.ManyToManyField(
                blank=True, related_name="favourites", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
