# Generated by Django 5.0.3 on 2024-04-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0005_trip_favourites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="favourites",
        ),
    ]
