# Generated by Django 5.0.3 on 2024-04-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0006_remove_trip_favourites"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TripDescription",
        ),
    ]
