# Generated by Django 5.0.3 on 2024-07-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0007_category_trip_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="category",
            new_name="categories",
        ),
    ]
