# Generated by Django 5.0.3 on 2024-07-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0008_rename_category_trip_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="categories",
        ),
        migrations.AddField(
            model_name="trip",
            name="categories",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="trips", to="trip.category"
            ),
        ),
    ]
