# Generated by Django 5.0.3 on 2024-07-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0011_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="trip_type",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="type", to="trip.type"
            ),
        ),
    ]
