# Generated by Django 5.0.3 on 2024-07-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0014_alter_trip_slug_remove_trip_trip_types_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="trip_types",
            new_name="trip_type",
        ),
    ]
