# Generated by Django 5.0.3 on 2024-07-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0015_rename_trip_types_trip_trip_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accommodation_info", models.CharField(max_length=255)),
                (
                    "accommodation_type",
                    models.ManyToManyField(
                        related_name="accommodations", to="trip.trip"
                    ),
                ),
            ],
        ),
    ]
