# Generated by Django 5.0.3 on 2024-07-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0016_accommodation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Accommodation",
        ),
    ]
