# Generated by Django 5.0.3 on 2024-07-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0017_delete_accommodation"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="accomondation_info",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
