# Generated by Django 5.0.3 on 2024-07-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0018_trip_accomondation_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accommondation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="accomondation_info",
            new_name="accommondation_info",
        ),
        migrations.AddField(
            model_name="trip",
            name="accommondation_type",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="accommondation",
                to="trip.accommondation",
            ),
        ),
    ]
