# Generated by Django 5.0.3 on 2024-07-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0019_accommondation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="accommondation_type",
            new_name="accommondation_types",
        ),
    ]
