# Generated by Django 5.0.3 on 2024-07-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0020_rename_accommondation_type_trip_accommondation_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="accommondation_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
