# Generated by Django 5.0.3 on 2024-07-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0021_alter_trip_accommondation_info"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Accommondation",
            new_name="Accommodation",
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="accommondation_info",
            new_name="accommodation_info",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="accommondation_types",
        ),
        migrations.AddField(
            model_name="trip",
            name="accommodation_types",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="accommodation",
                to="trip.accommodation",
            ),
        ),
    ]
