# Generated by Django 5.0.3 on 2024-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0024_remove_trip_inclusions"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="inclusions",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
