# Generated by Django 5.0.3 on 2024-07-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0025_trip_inclusions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="inclusions",
        ),
    ]
