# Generated by Django 5.0.3 on 2024-07-10 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0029_trip_inclusions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stops",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "duration",
                    models.IntegerField(
                        help_text="Duration in hours",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="trip",
            name="inclusions",
        ),
        migrations.AddField(
            model_name="trip",
            name="stops",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="stops", to="trip.stops"
            ),
        ),
    ]
