# Generated by Django 5.0.3 on 2024-07-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0030_stops_remove_trip_inclusions_trip_stops"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="stops",
        ),
        migrations.DeleteModel(
            name="Stops",
        ),
    ]
