# Generated by Django 5.0.3 on 2024-07-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0034_stop_trip_stops"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="stops",
        ),
        migrations.DeleteModel(
            name="Stop",
        ),
    ]
