# Generated by Django 5.0.3 on 2024-07-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0035_remove_trip_stops_delete_stop"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="stops",
            field=models.JSONField(default=list),
        ),
    ]
